### ISSUE TITLE
Unable to open .a7tinfo file in DLC: new world rising（data25.rda）

### ISSUE THREAD

**Issue by HowardXi** [anno-mods/AnnoMapEditor#41]
For the new world rising map, the editor has no effect after opening the file

Is there something wrong with my operation？ please let me know if there is any new information

**Comment by jakobharder** [comment]
There's no update released yet after GU16. You need to wait a bit to get that support, but it's worked on.

**Comment by HowardXi** [comment]
OK, thank you reply
